"""QA/DX Agent for continuous code hygiene.

This agent runs static analysis using tools like Vulture and Ruff to find dead code
and uses semantic checks (LLM-based) to cross-reference with the documentation.
"""

from __future__ import annotations

import ast
import json
import logging
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class DeadCodeItem:
    """Represents a piece of dead code identified by Vulture."""

    filepath: Path
    lineno: int
    end_lineno: int
    name: str
    typ: str
    message: str


@dataclass
class QAReport:
    """Report generated by the QAAgent."""

    items_removed: list[dict] = field(default_factory=list)
    semantic_deviations: list[dict] = field(default_factory=list)

    def to_json(self) -> str:
        """Convert the report to JSON."""
        return json.dumps(
            {
                "items_removed": self.items_removed,
                "semantic_deviations": self.semantic_deviations,
            }
        )


class DeadCodeVisitor(ast.NodeVisitor):
    """AST NodeVisitor to find the exact boundaries of elements to remove."""

    def __init__(self, target_line: int, target_name: str) -> None:
        self.target_line = target_line
        self.target_name = target_name
        self.node: ast.AST | None = None

    def _check_node(self, node: ast.AST, name: str) -> None:
        if getattr(node, "lineno", -1) == self.target_line and name == self.target_name:
            self.node = node

    def visit_FunctionDef(self, node: ast.FunctionDef) -> None:  # noqa: N802
        self._check_node(node, node.name)
        self.generic_visit(node)

    def visit_AsyncFunctionDef(self, node: ast.AsyncFunctionDef) -> None:  # noqa: N802
        self._check_node(node, node.name)
        self.generic_visit(node)

    def visit_ClassDef(self, node: ast.ClassDef) -> None:  # noqa: N802
        self._check_node(node, node.name)
        self.generic_visit(node)

    def visit_Import(self, node: ast.Import) -> None:  # noqa: N802
        for alias in node.names:
            if getattr(node, "lineno", -1) == self.target_line and alias.name == self.target_name:
                self.node = node
        self.generic_visit(node)

    def visit_ImportFrom(self, node: ast.ImportFrom) -> None:  # noqa: N802
        for alias in node.names:
            if getattr(node, "lineno", -1) == self.target_line and alias.name == self.target_name:
                self.node = node
        self.generic_visit(node)

    def visit_Assign(self, node: ast.Assign) -> None:  # noqa: N802
        for target in node.targets:
            if isinstance(target, ast.Name):
                self._check_node(node, target.id)
        self.generic_visit(node)

    def visit_AnnAssign(self, node: ast.AnnAssign) -> None:  # noqa: N802
        if isinstance(node.target, ast.Name):
            self._check_node(node, node.target.id)
        self.generic_visit(node)


class QAAgent:
    """Autonomous QA/DX agent for code hygiene."""

    def __init__(self, root_dir: Path | str = ".") -> None:
        self.root_dir = Path(root_dir).resolve()
        self.report = QAReport()

    def run(self, dry_run: bool = False, deep: bool = False) -> QAReport:
        """Execute the code hygiene pipeline."""
        logger.info(f"Running QAAgent on {self.root_dir} (deep={deep})")

        # 1. Run static analysis (Vulture)
        dead_items = self._run_vulture()

        # 2. Filter out documented components (cross-reference)
        removable_items = self._cross_reference_docs(dead_items)

        if not dry_run:
            # 3. Apply removals
            self._remove_dead_code(removable_items)

            # 4. Auto-fix with Ruff (formatting, missing docstrings, etc)
            self._run_ruff()

        return self.report

    def _run_vulture(self) -> list[DeadCodeItem]:
        """Run Vulture to detect dead code."""
        items: list[DeadCodeItem] = []
        try:
            import vulture  # type: ignore[import]
        except ImportError:
            logger.warning("Vulture is not installed. Skipping dead code analysis.")
            return items

        v = vulture.Vulture()
        paths = [
            str(p)
            for p in self.root_dir.rglob("*.py")
            if "tests/" not in str(p) and "docs/" not in str(p) and ".venv" not in str(p)
        ]
        if not paths:
            return items

        v.scavenge(paths)

        for item in v.get_unused_code():
            # For simplicity, filter out variables/properties that are hard to safely remove
            if item.typ in ("class", "function", "method", "import"):
                items.append(
                    DeadCodeItem(
                        filepath=Path(item.filename),
                        lineno=item.first_lineno,
                        end_lineno=item.last_lineno,
                        name=item.name,
                        typ=item.typ,
                        message=item.message,
                    )
                )

        return items

    def _cross_reference_docs(self, items: list[DeadCodeItem]) -> list[DeadCodeItem]:
        """Use semantic LLM checks to verify if a component is documented."""
        removable: list[DeadCodeItem] = []
        docs_dir = self.root_dir / "docs"
        docs_content = ""
        if docs_dir.exists():
            for doc_file in docs_dir.rglob("*.md"):
                docs_content += doc_file.read_text(encoding="utf-8") + "\\n"

        for item in items:
            # Mock LLM behavior: check if the item name appears in documentation
            # In a real environment, this would call an LLM API to understand context
            if item.name not in docs_content:
                removable.append(item)
            else:
                self.report.semantic_deviations.append(
                    {
                        "type": "documented_but_unused",
                        "name": item.name,
                        "filepath": str(item.filepath),
                        "message": f"Component '{item.name}' is documented but appears unused.",
                    }
                )

        return removable

    def _remove_dead_code(self, items: list[DeadCodeItem]) -> None:
        """Remove dead code identified by Vulture using AST."""
        # Group items by file
        from collections import defaultdict

        file_items: dict[Path, list[DeadCodeItem]] = defaultdict(list)
        for item in items:
            file_items[item.filepath].append(item)

        for filepath, f_items in file_items.items():
            try:
                content = filepath.read_text(encoding="utf-8")
                tree = ast.parse(content)
                source_lines = content.splitlines()

                # Replace nodes
                for item in f_items:
                    visitor = DeadCodeVisitor(target_line=item.lineno, target_name=item.name)
                    visitor.visit(tree)

                    node = visitor.node
                    if node and hasattr(node, "lineno") and hasattr(node, "end_lineno"):
                        # Replace lines with None to maintain indexing
                        start = node.lineno - 1
                        end = node.end_lineno
                        for i in range(start, end):
                            source_lines[i] = None  # type: ignore

                        self.report.items_removed.append(
                            {
                                "filepath": str(filepath.relative_to(self.root_dir)),
                                "name": item.name,
                                "type": item.typ,
                                "lines": f"{node.lineno}-{node.end_lineno}",
                            }
                        )
                    else:
                        # Fallback for simple single-line items like imports
                        source_lines[item.lineno - 1] = None  # type: ignore
                        self.report.items_removed.append(
                            {
                                "filepath": str(filepath.relative_to(self.root_dir)),
                                "name": item.name,
                                "type": item.typ,
                                "lines": str(item.lineno),
                            }
                        )

                # Reconstruct file
                new_content = "\\n".join(line for line in source_lines if line is not None)
                filepath.write_text(new_content + "\\n", encoding="utf-8")

            except Exception as exc:  # noqa: BLE001
                logger.error(f"Failed to remove code from {filepath}: {exc}")

    def _run_ruff(self) -> None:
        """Run Ruff in --fix mode to format and clean up remaining issues."""
        try:
            subprocess.run(
                [sys.executable, "-m", "ruff", "check", "--fix", str(self.root_dir)],
                check=False,
                capture_output=True,
            )
        except Exception as exc:  # noqa: BLE001
            logger.error(f"Failed to run ruff: {exc}")
