"""Autonomous QA & DX Agent for code hygiene and interface compliance."""

from __future__ import annotations

import json
import logging
import re
import subprocess
import os
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Basic types and structures


@dataclass
class QAReport:
    """Structured report generated by the QAAgent."""

    score_repo_health: float = 0.0
    score_docstring: float = 0.0
    cli_commands: list[str] = field(default_factory=list)
    makefile_targets: list[str] = field(default_factory=list)
    orphaned_commands: list[str] = field(default_factory=list)
    architectural_violations: list[str] = field(default_factory=list)
    test_coverage_issues: list[str] = field(default_factory=list)
    complexity_warnings: list[str] = field(default_factory=list)
    semantic_reviews: list[str] = field(default_factory=list)
    tool_outputs: dict[str, str] = field(default_factory=dict)
    summary: str = ""

    def to_dict(self) -> dict[str, Any]:
        """Convert the report to a dictionary for JSON serialization."""
        return asdict(self)


class QAAgent:
    """Agent responsible for code quality, docstrings, and architectural audits."""

    def __init__(self, root_dir: Path | str = ".") -> None:
        self.root_dir = Path(root_dir).resolve()

    def _run_tool(self, cmd: list[str], cwd: Path | None = None) -> str:
        """Run an external tool via subprocess and return its stdout + stderr."""
        try:
            result = subprocess.run(
                cmd,
                cwd=cwd or self.root_dir,
                capture_output=True,
                text=True,
                check=False,
            )
            return result.stdout + result.stderr
        except FileNotFoundError:
            return f"Error: Tool not found: {cmd[0]}"
        except Exception as e:  # noqa: BLE001
            return f"Error running {cmd[0]}: {e}"

    def audit_interfaces_and_commands(self) -> dict[str, Any]:
        """Check for consistency between CLI commands, Makefile, and docs."""
        cli_cmds: set[str] = set()
        makefile_targets: set[str] = set()
        orphaned: list[str] = []

        # 1. Parse Makefile
        makefile_path = self.root_dir / "Makefile"
        if makefile_path.exists():
            content = makefile_path.read_text(encoding="utf-8")
            for line in content.splitlines():
                match = re.match(r"^([a-zA-Z0-9_-]+):", line)
                if match and not line.startswith(".PHONY"):
                    makefile_targets.add(match.group(1))

        # 2. Heuristic parsing of CLI commands (Typer @app.command)
        # This is basic and reads source files
        cli_dir = self.root_dir / "aptdata" / "cli"
        if cli_dir.exists():
            for py_file in cli_dir.rglob("*.py"):
                content = py_file.read_text(encoding="utf-8")
                # Look for @app.command("name") or def name(
                for match in re.finditer(r'@[\w_]+\.command\s*\(\s*(?:"([^"]+)")?', content):
                    cmd_name = match.group(1)
                    if cmd_name:
                        cli_cmds.add(cmd_name)
                # Fallback for implicit names from function defs under @...command()
                for match in re.finditer(r'@[\w_]+\.command.*?\n(?:@.*?\n)*def\s+([a-zA-Z0-9_]+)\s*\(', content, re.DOTALL):
                    cmd_name = match.group(1).replace("_", "-")
                    cli_cmds.add(cmd_name)

        # 3. Very basic doc check for Makefile targets (are they mentioned in README/docs?)
        docs_text = ""
        readme_path = self.root_dir / "README.md"
        if readme_path.exists():
            docs_text += readme_path.read_text(encoding="utf-8")
        docs_dir = self.root_dir / "docs"
        if docs_dir.exists():
            for doc_file in docs_dir.rglob("*.md"):
                docs_text += doc_file.read_text(encoding="utf-8")

        for target in makefile_targets:
            if target not in docs_text:
                orphaned.append(target)

        return {
            "cli_commands": sorted(cli_cmds),
            "makefile_targets": sorted(makefile_targets),
            "orphaned_commands": orphaned,
        }

    def audit_architecture(self) -> list[str]:
        """Look for architectural violations like Pandas in core or dict inputs."""
        violations = []
        core_dir = self.root_dir / "aptdata" / "core"
        if core_dir.exists():
            for py_file in core_dir.rglob("*.py"):
                content = py_file.read_text(encoding="utf-8")
                # 1. Pandas coupling in core
                if re.search(r"import\s+pandas|from\s+pandas\s+import", content):
                    violations.append(
                        f"Architectural Violation: Pandas coupling found in {py_file.relative_to(self.root_dir)}"
                    )

                # 2. Contract-First violations: look for methods taking raw dicts as dataset inputs
                # This regex is a heuristic looking for `def execute(... -> dict` or `def execute(..., x: dict)`
                # Real implementation would use AST.
                if re.search(r"def\s+execute\s*\([^)]*:\s*dict[^)]*\)", content):
                    violations.append(
                         f"Contract-First Violation: pure dict used in execute signature in {py_file.relative_to(self.root_dir)}"
                    )
        return violations

    def audit_tests(self) -> list[str]:
        """Check for missing unit tests for core and plugin modules."""
        issues = []
        for d in ["core", "plugins"]:
            target_dir = self.root_dir / "aptdata" / d
            if target_dir.exists():
                for py_file in target_dir.rglob("*.py"):
                    if py_file.name == "__init__.py":
                        continue

                    # Assume tests are in tests/test_<name>.py or tests/<d>/test_<name>.py
                    rel_path = py_file.relative_to(self.root_dir / "aptdata")
                    test_name = f"test_{py_file.name}"

                    test_path_flat = self.root_dir / "tests" / test_name
                    test_path_nested = self.root_dir / "tests" / rel_path.parent / test_name

                    if not test_path_flat.exists() and not test_path_nested.exists():
                        issues.append(f"Missing unit test for {py_file.relative_to(self.root_dir)}")
        return issues

    def evaluate_semantics_with_llm(self, docstring: str, code: str) -> str:
        """Use an LLM to evaluate if the docstring makes sense for the code."""
        api_key = os.environ.get("OPENAI_API_KEY")
        if not api_key:
            return "Skipped LLM semantic evaluation (OPENAI_API_KEY not set)."

        try:
            import httpx

            prompt = (
                "Você é um engenheiro de software experiente. "
                "Avalie se a seguinte docstring faz sentido e descreve corretamente "
                "o código fornecido. Responda de forma concisa em português.\n\n"
                f"Docstring:\n{docstring}\n\nCódigo:\n{code}"
            )

            response = httpx.post(
                "https://api.openai.com/v1/chat/completions",
                headers={"Authorization": f"Bearer {api_key}"},
                json={
                    "model": "gpt-4o",
                    "messages": [{"role": "user", "content": prompt}],
                    "max_tokens": 150,
                    "temperature": 0.0
                },
                timeout=10.0
            )
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"].strip()
        except Exception as e: # noqa: BLE001
            return f"LLM Error: {e}"

    def run_static_analysis(self, deep: bool = False) -> dict[str, str]:
        """Run ruff, mypy, and pydocstyle."""
        outputs = {}
        # Ruff (include C901 for cyclomatic complexity if not default, but we can just run it)
        outputs["ruff"] = self._run_tool(["ruff", "check", "--select", "E,F,I,W,UP,C90", "aptdata/"])

        if deep:
            # MyPy
            outputs["mypy"] = self._run_tool(["mypy", "aptdata/"])
            # pydocstyle (or ruff equivalents, but using pydocstyle if available)
            outputs["pydocstyle"] = self._run_tool(["pydocstyle", "aptdata/core/"])

        return outputs

    def compute_scores(self, tool_outputs: dict[str, str], violations: list[str], test_issues: list[str]) -> tuple[float, float]:
        """Compute pseudo scores for repo health and docstrings."""
        repo_health = 100.0
        docstring_score = 100.0

        # Penalize for ruff errors
        ruff_out = tool_outputs.get("ruff", "")
        if "Found" in ruff_out and "errors" in ruff_out:
            repo_health -= 10.0

        # Penalize for arch violations
        repo_health -= len(violations) * 5.0

        # Penalize for missing tests
        repo_health -= len(test_issues) * 2.0

        # Penalize docstrings
        pydoc_out = tool_outputs.get("pydocstyle", "")
        missing_docs = len(re.findall(r"Missing docstring", pydoc_out, re.IGNORECASE))
        docstring_score -= missing_docs * 2.0

        return max(0.0, repo_health), max(0.0, docstring_score)

    def analyze(self, deep: bool = False) -> QAReport:
        """Run the full QA analysis and return a QAReport."""
        iface_data = self.audit_interfaces_and_commands()
        violations = self.audit_architecture()
        test_issues = self.audit_tests()
        tools_out = self.run_static_analysis(deep=deep)

        complexity_warnings = []
        if "ruff" in tools_out:
            # Look for cyclomatic complexity warnings (e.g. C901)
            for line in tools_out["ruff"].splitlines():
                if "C901" in line:
                    complexity_warnings.append(line.strip())

        semantic_reviews = []
        if deep and os.environ.get("OPENAI_API_KEY"):
            # Sample semantic review for the BaseComponent
            core_file = self.root_dir / "aptdata" / "core" / "system.py"
            if core_file.exists():
                content = core_file.read_text(encoding="utf-8")
                # Very simple extraction for demo purposes
                match = re.search(r'class BaseComponent.*?:(.*?)def', content, re.DOTALL)
                if match:
                    class_body = match.group(1)
                    doc_match = re.search(r'"""(.*?)"""', class_body, re.DOTALL)
                    if doc_match:
                        docstring = doc_match.group(1)
                        eval_res = self.evaluate_semantics_with_llm(docstring, class_body)
                        semantic_reviews.append(f"BaseComponent Docstring Semantics: {eval_res}")
        elif deep:
             semantic_reviews.append("Skipped LLM semantic evaluation (OPENAI_API_KEY not set).")

        health_score, doc_score = self.compute_scores(tools_out, violations, test_issues)

        summary = "QA Analysis completed. "
        if violations:
            summary += f"Found {len(violations)} architectural violations. "
        if iface_data["orphaned_commands"]:
            summary += f"Found {len(iface_data['orphaned_commands'])} undocumented Makefile targets. "
        if test_issues:
            summary += f"Found {len(test_issues)} files missing tests. "

        return QAReport(
            score_repo_health=health_score,
            score_docstring=doc_score,
            cli_commands=iface_data["cli_commands"],
            makefile_targets=iface_data["makefile_targets"],
            orphaned_commands=iface_data["orphaned_commands"],
            architectural_violations=violations,
            test_coverage_issues=test_issues,
            complexity_warnings=complexity_warnings,
            semantic_reviews=semantic_reviews,
            tool_outputs=tools_out,
            summary=summary.strip() or "All checks passed.",
        )
